media: public/img
content:
  - name: posts
    label: Missionários
    type: collection
    path: content/missionarios
    view:
      fields: [ pageTitle, title, draft, date ]
    fields:
      - { name: pageTitle, label: Título Página, type: string, required: true }
      - { name: title, label: Título, type: string, required: true }
      - { name: description, label: Descrição, type: string }
      - { name: phone1, label: Telefone, type: string }
      - { name: phone2, label: Telefone, type: string }
      - { name: date, label: Data publicação, type: date }
      - { name: birthDate, label: Data de Nascimento, type: date }
      - { name: weddingAnniversary, label: Aniversário de casamento, type: date }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Conteúdo, type: rich-text }
  - name: about
    label: About page
    type: file
    path: content/about/index.md
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, label: Key, type: string }
          - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
  - name: metadata
    label: Metadata
    type: file
    path: _data/metadata.js
    format: code
